In [33]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder,OneHotEncoder
import pickle

In [34]:
data  = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [35]:
data.columns

Index(['RowNumber', 'CustomerId', 'Surname', 'CreditScore', 'Geography',
       'Gender', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
       'IsActiveMember', 'EstimatedSalary', 'Exited'],
      dtype='str')

In [36]:
## Processing the data
## delete RowNumber,CustomerId,Surname
data = data.drop(['RowNumber','CustomerId','Surname'],axis =1)

In [37]:
# Encode the categorical variables
label_encoder = LabelEncoder()
data['Gender'] = label_encoder.fit_transform(data['Gender'])

In [38]:
## One-Hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder()
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns = onehot_encoder_geo.get_feature_names_out(['Geography']))

In [39]:
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [40]:
## Combining One-Hot encode 'Geography' and original data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [41]:
## split the data
## Dependent feature -> EstimatedSalary
# INdependent features -> all except EstimatedSalary
X = data.drop('EstimatedSalary',axis=1)
y = data['EstimatedSalary']

In [42]:
# split the data
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.20,random_state=42)

In [43]:
## Scale these Features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [44]:
# X_train = np.asarray(X_train, dtype=np.float32)
# X_test  = np.asarray(X_test, dtype=np.float32)

# y_train = np.asarray(y_train, dtype=np.float32)
# y_test  = np.asarray(y_test, dtype=np.float32)

In [45]:
## Save the encoders and scaler for later use
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('label_encoder.pkl','wb') as file:
    pickle.dump(label_encoder,file)

with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem statement

In [46]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [47]:
## Build the Model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),## HL1 Connected with input layer
    Dense(32,activation='relu'),## HL2
    Dense(1) # Output layer for regression ,by default activation=linear regresssion
])
 
## Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()
print(model.input_shape)

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_11 (Dense)            (None, 64)                832

 dense_12 (Dense)            (None, 32)                2080

 dense_13 (Dense)            (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
(None, 12)

# Callbacks :-
Callbacks are functions that automatically execute during model training to monitor, control, or modify the training process.

Examples: EarlyStopping stops training when performance stops improving, and TensorBoard logs training metrics for visualization. 🚀

In [48]:
import tensorflow as tf
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime
## Setup tensor board
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1  
)

In [49]:
## Setup tensorboard
early_stopping_callback = EarlyStopping(
    monitor='val_loss',
    patience=10,
    restore_best_weights=True
)

In [50]:
## Model Training
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 5s 18ms/step - loss: 100423.1406 - mae: 100423.1406 - val_loss: 98695.9688 - val_mae: 98695.9688
Epoch 2/100
250/250 [==============================] - 2s 7ms/step - loss: 100341.6719 - mae: 100341.6719 - val_loss: 98552.7031 - val_mae: 98552.7031
Epoch 3/100
250/250 [==============================] - 2s 9ms/step - loss: 100155.6641 - mae: 100155.6641 - val_loss: 98316.6875 - val_mae: 98316.6875
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 99886.8438 - mae: 99886.8438 - val_loss: 98010.2266 - val_mae: 98010.2266
Epoch 5/100
250/250 [==============================] - 3s 13ms/step - loss: 99562.3359 - mae: 99562.3359 - val_loss: 97659.0859 - val_mae: 97659.0859
Epoch 6/100
250/250 [==============================] - 3s 13ms/step - loss: 99216.5625 - mae: 99216.5625 - val_loss: 97315.0000 - val_mae: 97315.0000
Epoch 7/100
250/250 [==============================] - 3s 12ms/step - loss: 98869.5234 - mae: 98869.5234 - val_loss: 97000.9062 - val_mae: 97000.9062
Epoch 8/100
250/250 [==============================] - 3s 11ms/step - loss: 98536.5391 - mae: 98536.5391 - val_loss: 96696.8984 - val_mae: 96696.8984
Epoch 9/100
250/250 [==============================] - 3s 13ms/step - loss: 98216.8984 - mae: 98216.8984 - val_loss: 96375.4766 - val_mae: 96375.4766
Epoch 10/100
250/250 [==============================] - 2s 9ms/step - loss: 97887.4844 - mae: 97887.4844 - val_loss: 96013.9922 - val_mae: 96013.9922
Epoch 11/100
250/250 [==============================] - 2s 8ms/step - loss: 97490.1328 - mae: 97490.1328 - val_loss: 95620.0859 - val_mae: 95620.0859
Epoch 12/100
250/250 [==============================] - 3s 12ms/step - loss: 97096.9062 - mae: 97096.9062 - val_loss: 95205.7266 - val_mae: 95205.7266
Epoch 13/100
250/250 [==============================] - 3s 11ms/step - loss: 96685.3359 - mae: 96685.3359 - val_loss: 94751.3516 - val_mae: 94751.3516
Epoch 14/100
250/250 [==============================] - 2s 10ms/step - loss: 96246.3125 - mae: 96246.3125 - val_loss: 94276.1875 - val_mae: 94276.1875
Epoch 15/100
250/250 [==============================] - 3s 11ms/step - loss: 95802.4531 - mae: 95802.4531 - val_loss: 93799.0469 - val_mae: 93799.0469
Epoch 16/100
250/250 [==============================] - 2s 8ms/step - loss: 95321.9453 - mae: 95321.9453 - val_loss: 93358.1328 - val_mae: 93358.1328
Epoch 17/100
250/250 [==============================] - 2s 8ms/step - loss: 94878.4609 - mae: 94878.4609 - val_loss: 92887.1016 - val_mae: 92887.1016
Epoch 18/100
250/250 [==============================] - 2s 7ms/step - loss: 94417.3672 - mae: 94417.3672 - val_loss: 92415.8750 - val_mae: 92415.8750
Epoch 19/100
250/250 [==============================] - 2s 8ms/step - loss: 93952.6328 - mae: 93952.6328 - val_loss: 91944.5781 - val_mae: 91944.5781
Epoch 20/100
250/250 [==============================] - 2s 9ms/step - loss: 93454.3672 - mae: 93454.3672 - val_loss: 91514.6016 - val_mae: 91514.6016
Epoch 21/100
250/250 [==============================] - 2s 7ms/step - loss: 92987.5781 - mae: 92987.5781 - val_loss: 90986.0547 - val_mae: 90986.0547
Epoch 22/100
250/250 [==============================] - 2s 9ms/step - loss: 92482.0000 - mae: 92482.0000 - val_loss: 90498.0234 - val_mae: 90498.0234
Epoch 23/100
250/250 [==============================] - 3s 10ms/step - loss: 91961.6719 - mae: 91961.6719 - val_loss: 89935.4453 - val_mae: 89935.4453
Epoch 24/100
250/250 [==============================] - 2s 8ms/step - loss: 91429.3984 - mae: 91429.3984 - val_loss: 89429.6172 - val_mae: 89429.6172
Epoch 25/100
250/250 [==============================] - 2s 8ms/step - loss: 90906.9375 - mae: 90906.9375 - val_loss: 88940.1016 - val_mae: 88940.1016
Epoch 26/100
250/250 [==============================] - 2s 8ms/step - loss: 90393.5469 - mae: 90393.5469 - val_loss: 88378.7109 - val_mae: 88378.7109
Epoch 27/100
250/250 [==============================] - 2s 8ms/step - loss: 89841.5859 - mae: 89841.5859 - val_loss: 87820.3984 - val_mae: 87820.3984
Epoch 28/100
250/250 [==============================] - 2s 8ms/step - loss: 89296.0938 - mae: 89296.0938 - val_loss: 87267.7031 - val_mae: 87267.7031
Epoch 29/100
250/250 [==============================] - 2s 8ms/step - loss: 88748.0625 - mae: 88748.0625 - val_loss: 86801.9531 - val_mae: 86801.9531
Epoch 30/100
250/250 [==============================] - 2s 8ms/step - loss: 88189.6797 - mae: 88189.6797 - val_loss: 86168.7188 - val_mae: 86168.7188
Epoch 31/100
250/250 [==============================] - 2s 8ms/step - loss: 87619.0703 - mae: 87619.0703 - val_loss: 85594.5078 - val_mae: 85594.5078
Epoch 32/100
250/250 [==============================] - 2s 7ms/step - loss: 87048.9453 - mae: 87048.9453 - val_loss: 85013.1250 - val_mae: 85013.1250
Epoch 33/100
250/250 [==============================] - 2s 8ms/step - loss: 86428.8828 - mae: 86428.8828 - val_loss: 84483.9141 - val_mae: 84483.9141
Epoch 34/100
250/250 [==============================] - 4s 14ms/step - loss: 85852.8906 - mae: 85852.8906 - val_loss: 83934.1797 - val_mae: 83934.1797
Epoch 35/100
250/250 [==============================] - 2s 8ms/step - loss: 85266.0469 - mae: 85266.0469 - val_loss: 83283.8203 - val_mae: 83283.8203
Epoch 36/100
250/250 [==============================] - 2s 8ms/step - loss: 84635.5625 - mae: 84635.5625 - val_loss: 82663.0000 - val_mae: 82663.0000
Epoch 37/100
250/250 [==============================] - 2s 8ms/step - loss: 84050.6250 - mae: 84050.6250 - val_loss: 82119.6328 - val_mae: 82119.6328
Epoch 38/100
250/250 [==============================] - 2s 7ms/step - loss: 83427.7969 - mae: 83427.7969 - val_loss: 81589.2891 - val_mae: 81589.2891
Epoch 39/100
250/250 [==============================] - 2s 9ms/step - loss: 82838.2188 - mae: 82838.2188 - val_loss: 80843.8203 - val_mae: 80843.8203
Epoch 40/100
250/250 [==============================] - 2s 8ms/step - loss: 82162.0547 - mae: 82162.0547 - val_loss: 80211.9453 - val_mae: 80211.9453
Epoch 41/100
250/250 [==============================] - 2s 8ms/step - loss: 81530.9297 - mae: 81530.9297 - val_loss: 79686.0312 - val_mae: 79686.0312
Epoch 42/100
250/250 [==============================] - 2s 8ms/step - loss: 80912.8516 - mae: 80912.8516 - val_loss: 78923.4453 - val_mae: 78923.4453
Epoch 43/100
250/250 [==============================] - 2s 8ms/step - loss: 80225.4844 - mae: 80225.4844 - val_loss: 78275.2031 - val_mae: 78275.2031
Epoch 44/100
250/250 [==============================] - 2s 7ms/step - loss: 79570.9141 - mae: 79570.9141 - val_loss: 77635.9531 - val_mae: 77635.9531
Epoch 45/100
250/250 [==============================] - 2s 7ms/step - loss: 78911.5859 - mae: 78911.5859 - val_loss: 77006.7812 - val_mae: 77006.7812
Epoch 46/100
250/250 [==============================] - 2s 8ms/step - loss: 78266.2578 - mae: 78266.2578 - val_loss: 76355.4922 - val_mae: 76355.4922
Epoch 47/100
250/250 [==============================] - 2s 9ms/step - loss: 77569.6172 - mae: 77569.6172 - val_loss: 75677.8438 - val_mae: 75677.8438
Epoch 48/100
250/250 [==============================] - 2s 8ms/step - loss: 76938.2656 - mae: 76938.2656 - val_loss: 75027.9297 - val_mae: 75027.9297
Epoch 49/100
250/250 [==============================] - 2s 8ms/step - loss: 76233.8750 - mae: 76233.8750 - val_loss: 74348.8281 - val_mae: 74348.8281
Epoch 50/100
250/250 [==============================] - 2s 8ms/step - loss: 75551.0234 - mae: 75551.0234 - val_loss: 73734.8281 - val_mae: 73734.8281
Epoch 51/100
250/250 [==============================] - 2s 8ms/step - loss: 74863.9531 - mae: 74863.9531 - val_loss: 73043.9688 - val_mae: 73043.9688
Epoch 52/100
250/250 [==============================] - 2s 7ms/step - loss: 74157.3750 - mae: 74157.3750 - val_loss: 72350.7812 - val_mae: 72350.7812
Epoch 53/100
250/250 [==============================] - 2s 8ms/step - loss: 73499.2188 - mae: 73499.2188 - val_loss: 71664.8672 - val_mae: 71664.8672
Epoch 54/100
250/250 [==============================] - 2s 8ms/step - loss: 72806.5469 - mae: 72806.5469 - val_loss: 71081.7422 - val_mae: 71081.7422
Epoch 55/100
250/250 [==============================] - 2s 8ms/step - loss: 72113.8047 - mae: 72113.8047 - val_loss: 70316.8125 - val_mae: 70316.8125
Epoch 56/100
250/250 [==============================] - 2s 8ms/step - loss: 71441.2734 - mae: 71441.2734 - val_loss: 69804.2500 - val_mae: 69804.2500
Epoch 57/100
250/250 [==============================] - 2s 8ms/step - loss: 70768.6094 - mae: 70768.6094 - val_loss: 69082.3281 - val_mae: 69082.3281
Epoch 58/100
250/250 [==============================] - 2s 7ms/step - loss: 70102.2109 - mae: 70102.2109 - val_loss: 68353.6406 - val_mae: 68353.6406
Epoch 59/100
250/250 [==============================] - 2s 7ms/step - loss: 69389.1953 - mae: 69389.1953 - val_loss: 67661.0078 - val_mae: 67661.0078
Epoch 60/100
250/250 [==============================] - 2s 8ms/step - loss: 68690.4531 - mae: 68690.4531 - val_loss: 66954.8906 - val_mae: 66954.8906
Epoch 61/100
250/250 [==============================] - 2s 8ms/step - loss: 67966.3438 - mae: 67966.3438 - val_loss: 66266.5312 - val_mae: 66266.5312
Epoch 62/100
250/250 [==============================] - 2s 8ms/step - loss: 67302.5781 - mae: 67302.5781 - val_loss: 65589.9531 - val_mae: 65589.9531
Epoch 63/100
250/250 [==============================] - 2s 8ms/step - loss: 66588.8047 - mae: 66588.8047 - val_loss: 64943.7617 - val_mae: 64943.7617
Epoch 64/100
250/250 [==============================] - 2s 8ms/step - loss: 65888.1484 - mae: 65888.1484 - val_loss: 64254.0742 - val_mae: 64254.0742
Epoch 65/100
250/250 [==============================] - 2s 9ms/step - loss: 65210.6094 - mae: 65210.6094 - val_loss: 63599.6172 - val_mae: 63599.6172
Epoch 66/100
250/250 [==============================] - 2s 9ms/step - loss: 64537.6250 - mae: 64537.6250 - val_loss: 63146.3555 - val_mae: 63146.3555
Epoch 67/100
250/250 [==============================] - 2s 8ms/step - loss: 63847.6680 - mae: 63847.6680 - val_loss: 62326.0352 - val_mae: 62326.0352
Epoch 68/100
250/250 [==============================] - 2s 8ms/step - loss: 63201.1758 - mae: 63201.1758 - val_loss: 62007.6250 - val_mae: 62007.6250
Epoch 69/100
250/250 [==============================] - 3s 12ms/step - loss: 62552.6523 - mae: 62552.6523 - val_loss: 61369.5625 - val_mae: 61369.5625
Epoch 70/100
250/250 [==============================] - 3s 12ms/step - loss: 61910.8711 - mae: 61910.8711 - val_loss: 60505.6680 - val_mae: 60505.6680
Epoch 71/100
250/250 [==============================] - 3s 10ms/step - loss: 61302.8750 - mae: 61302.8750 - val_loss: 59937.6523 - val_mae: 59937.6523
Epoch 72/100
250/250 [==============================] - 3s 12ms/step - loss: 60650.0039 - mae: 60650.0039 - val_loss: 59291.6719 - val_mae: 59291.6719
Epoch 73/100
250/250 [==============================] - 2s 10ms/step - loss: 60054.3438 - mae: 60054.3438 - val_loss: 58727.7578 - val_mae: 58727.7578
Epoch 74/100
250/250 [==============================] - 2s 9ms/step - loss: 59386.4805 - mae: 59386.4805 - val_loss: 58181.1680 - val_mae: 58181.1680
Epoch 75/100
250/250 [==============================] - 2s 8ms/step - loss: 58782.7070 - mae: 58782.7070 - val_loss: 57598.6133 - val_mae: 57598.6133
Epoch 76/100
250/250 [==============================] - 2s 8ms/step - loss: 58182.2617 - mae: 58182.2617 - val_loss: 57033.4531 - val_mae: 57033.4531
Epoch 77/100
250/250 [==============================] - 3s 14ms/step - loss: 57541.3125 - mae: 57541.3125 - val_loss: 56517.0039 - val_mae: 56517.0039
Epoch 78/100
250/250 [==============================] - 3s 14ms/step - loss: 57040.7969 - mae: 57040.7969 - val_loss: 56027.7969 - val_mae: 56027.7969
Epoch 79/100
250/250 [==============================] - 3s 13ms/step - loss: 56502.8867 - mae: 56502.8867 - val_loss: 55554.3555 - val_mae: 55554.3555
Epoch 80/100
250/250 [==============================] - 3s 11ms/step - loss: 55975.6992 - mae: 55975.6992 - val_loss: 55029.3203 - val_mae: 55029.3203
Epoch 81/100
250/250 [==============================] - 2s 8ms/step - loss: 55457.6328 - mae: 55457.6328 - val_loss: 54581.4141 - val_mae: 54581.4141
Epoch 82/100
250/250 [==============================] - 2s 8ms/step - loss: 54965.2383 - mae: 54965.2383 - val_loss: 54291.9883 - val_mae: 54291.9883
Epoch 83/100
250/250 [==============================] - 2s 8ms/step - loss: 54497.3242 - mae: 54497.3242 - val_loss: 53730.9492 - val_mae: 53730.9492
Epoch 84/100
250/250 [==============================] - 2s 8ms/step - loss: 54025.2656 - mae: 54025.2656 - val_loss: 53547.4414 - val_mae: 53547.4414
Epoch 85/100
250/250 [==============================] - 3s 13ms/step - loss: 53603.3555 - mae: 53603.3555 - val_loss: 53067.9688 - val_mae: 53067.9688
Epoch 86/100
250/250 [==============================] - 3s 10ms/step - loss: 53225.8906 - mae: 53225.8906 - val_loss: 52550.1289 - val_mae: 52550.1289
Epoch 87/100
250/250 [==============================] - 3s 11ms/step - loss: 52820.6211 - mae: 52820.6211 - val_loss: 52188.1367 - val_mae: 52188.1367
Epoch 88/100
250/250 [==============================] - 2s 8ms/step - loss: 52389.5391 - mae: 52389.5391 - val_loss: 52091.6406 - val_mae: 52091.6406
Epoch 89/100
250/250 [==============================] - 2s 8ms/step - loss: 52039.5430 - mae: 52039.5430 - val_loss: 51623.9492 - val_mae: 51623.9492
Epoch 90/100
250/250 [==============================] - 2s 8ms/step - loss: 51727.4258 - mae: 51727.4258 - val_loss: 51305.1250 - val_mae: 51305.1250
Epoch 91/100
250/250 [==============================] - 2s 8ms/step - loss: 51429.5781 - mae: 51429.5781 - val_loss: 51205.2852 - val_mae: 51205.2852
Epoch 92/100
250/250 [==============================] - 2s 8ms/step - loss: 51245.0508 - mae: 51245.0508 - val_loss: 50990.5664 - val_mae: 50990.5664
Epoch 93/100
250/250 [==============================] - 2s 8ms/step - loss: 50898.2344 - mae: 50898.2344 - val_loss: 50779.0469 - val_mae: 50779.0469
Epoch 94/100
250/250 [==============================] - 2s 8ms/step - loss: 50717.7969 - mae: 50717.7969 - val_loss: 50633.5312 - val_mae: 50633.5312
Epoch 95/100
250/250 [==============================] - 2s 7ms/step - loss: 50537.9805 - mae: 50537.9805 - val_loss: 50512.5625 - val_mae: 50512.5625
Epoch 96/100
250/250 [==============================] - 2s 8ms/step - loss: 50364.3633 - mae: 50364.3633 - val_loss: 50524.4727 - val_mae: 50524.4727
Epoch 97/100
250/250 [==============================] - 2s 8ms/step - loss: 50270.1211 - mae: 50270.1211 - val_loss: 50588.7852 - val_mae: 50588.7852
Epoch 98/100
250/250 [==============================] - 2s 8ms/step - loss: 50166.4375 - mae: 50166.4375 - val_loss: 50304.5508 - val_mae: 50304.5508
Epoch 99/100
250/250 [==============================] - 2s 8ms/step - loss: 50093.8359 - mae: 50093.8359 - val_loss: 50260.2266 - val_mae: 50260.2266
Epoch 100/100
250/250 [==============================] - 2s 8ms/step - loss: 49986.6367 - mae: 49986.6367 - val_loss: 50216.9258 - val_mae: 50216.9258

In [51]:
## Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [52]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 3818), started 0:24:32 ago. (Use '!kill 3818' to kill it.)

In [59]:
model.save('regression_model.h5')

In [54]:
## Evaluate model on the test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE: {test_mae}")

63/63 [==============================] - 0s 6ms/step - loss: 50216.9258 - mae: 50216.9258
Test MAE: 50216.92578125